# Generated by Django 3.2 on 2021-05-29 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.audio')),
            ],
        ),
    ]
