# Generated by Django 3.2 on 2021-05-29 05:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_auto_20210529_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='name',
        ),
        migrations.AddField(
            model_name='transcription',
            name='audio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='audio.audio'),
            preserve_default=False,
        ),
    ]
