# Generated by Django 3.2 on 2021-05-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_auto_20210529_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='audio',
            new_name='name',
        ),
    ]
