# Generated by Django 3.2 on 2021-05-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_rename_audio_transcription_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='name',
            new_name='audio',
        ),
    ]
