# Generated by Django 3.2 on 2021-06-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='genre',
            field=models.CharField(choices=[('podcast', 'Podcast'), ('audioBook', 'AudioBook'), ('music', 'Music')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
